# Generated by Django 3.2.15 on 2022-10-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20221008_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Site1',
        ),
    ]
