# Generated by Django 3.2.15 on 2022-10-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_rename_site_site1'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('DC_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DC_name', models.CharField(max_length=200)),
            ],
        ),
    ]
