# Generated by Django 3.2.15 on 2022-10-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_idc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site1',
        ),
    ]
