# Generated by Django 3.2.15 on 2022-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Country Population Data',
            },
        ),
    ]
