# Generated by Django 3.2.15 on 2023-01-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDue',
            fields=[
                ('number', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskjira', models.CharField(max_length=500)),
                ('taskcreate', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('taskend', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('excecute', models.CharField(choices=[('Lê Minh Đức', 'Lê Minh Đức'), ('Phạm Đình Nghĩa', 'Phạm Đình Nghĩa'), ('Hà Văn Huân', 'Hà Văn Huân'), ('Nguyễn Khắc Xuân Tùng', 'Nguyễn Khắc Xuân Tùng'), ('Nguyễn Tiến Dũng', 'Nguyễn Tiến Dũng'), ('Nguyễn Kế Toàn', 'Nguyễn Kế Toàn'), ('Nguyễn An', 'Nguyễn An'), ('Hà Đa Sĩ', 'Hà Đa Sĩ')], max_length=200)),
                ('request', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Trung tâm Điều hành IT', 'Trung tâm Điều hành IT'), ('Trung tâm Chính phủ điện tử', 'Trung tâm Chính phủ điện tử'), ('Trung tâm Y tế điện tử', 'Trung tâm Y tế điện tử'), ('Trung tâm Sáng tạo (IC)', 'Trung tâm Sáng tạo (IC)'), ('Trung tâm Giáo dục điện tử', 'Trung tâm Giáo dục điện tử'), ('Trung tâm Giải pháp tích hợp hệ thống', 'Trung tâm Giải pháp tích hợp hệ thống'), ('Trung tâm An toàn thông tin', 'Trung tâm An toàn thông tin'), ('Trung tâm giải pháp Quản trị doanh nghiệp', 'Trung tâm giải pháp Quản trị doanh nghiệp'), ('Trung tâm IT Khu vực 1', 'Trung tâm IT Khu vực 1'), ('Trung tâm IT Khu vực 2', 'Trung tâm IT Khu vực 2'), ('Trung tâm IT Khu vực 3', 'Trung tâm IT Khu vực 3'), ('Trung tâm IT Khu vực 4', 'Trung tâm IT Khu vực 4'), ('Trung tâm IT Khu vực 5', 'Trung tâm IT Khu vực 5'), ('Ban Kỹ thuật hạ tầng', 'Ban Kỹ thuật hạ tầng'), ('Trung tâm Hạ tầng IDC', 'Trung tâm Hạ tầng IDC'), ('Ban Chất lượng sản phẩm', 'Ban Chất lượng sản phẩm'), ('Ban Tiếp thị Bán hàng', 'Ban Tiếp thị Bán hàng'), ('Ban Kế toán Tài chính', 'Ban Kế toán Tài chính'), ('Ban Chiến lược sản phẩm', 'Ban Chiến lược sản phẩm'), ('Ban Kế hoạch Đầu tư', 'Ban Kế hoạch Đầu tư'), ('Ban Quản lý dự án', 'Ban Quản lý dự án'), ('Viễn thông tỉnh', 'Viễn thông tỉnh')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Task Expired',
            },
        ),
    ]
