# Generated by Django 3.2.15 on 2023-02-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_taskdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdue',
            name='taskcreate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskdue',
            name='taskjira',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
