# Generated by Django 4.1.7 on 2023-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdue',
            name='taskcreate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskdue',
            name='taskend',
            field=models.DateField(),
        ),
    ]
