# Generated by Django 4.1.7 on 2023-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_taskdue_taskcreate_alter_taskdue_taskend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdue',
            name='taskcreate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskdue',
            name='taskend',
            field=models.DateTimeField(),
        ),
    ]
